### ISSUE TITLE
Could we export the Collections also as type to make use of the models in the sdk

### ISSUE THREAD

**Issue by michael-scheurer** [ChappIO/directus-extension-models#1]
We could make use of the Collections in the Directus SDK. But `const directus = new Directus<Collections>('url')` wouldn't work, because the `<Collections>` must extend from `TypeMap` by definition. To overcome this, we could simply generate the Collections also as type.

That way:

```
export type DirectusCollections = {
  directus_folders: DirectusFolder;
  directus_roles: DirectusRole;
  ...
}
```

What do you think?

**Comment by ChappIO** [comment]
Have you tested this for your use-case? If that works I'm all for it, but I did not make this extension for the Directus sdk. I explicitly developed it to improve the development experience of developing extension.

Let me know if you tested this, how you tested it and how it worked for you.

You don't have to change Chappio/directus-extension-models to test it, just edit the generated sources and try to run your application. If that works well for you I will consider publishing the change in this repo.

**Comment by michael-scheurer** [comment]
Indeed, I'm testing it on a new project for some days now and it perfectly works.
In my case it makes the front-end development work combined with the sdk way more simpler or at least type safer.
I would definitely recommend it.
...and drop a hint in the docs ;) I could open a PR once the change here is made.

**Comment by ChappIO** [comment]
Thanks, it took a moment for me to find the time but I created a new release 2.1.0 which has this change.
