### ISSUE TITLE
Types of field parameter inside readItems is incomplete

### ISSUE THREAD

**Issue by thijserven** [ChappIO/directus-extension-models#15]
First of all... great job on the library! I've decided to give it a try today and the schema generates very nicely.

However I found one little issue.

When I set up the generated schema inside`createDirectus()` function of the Directus SDK (like demonstrated inside the README.md). And try to read items that include nested relational data, the type hinting doesn't work beyond the first level of data.

For example when I have a function like this:
```js
    const items = await directus.request(
        readItems("items", {
            fields: [
                "id",
                "name",
                "images.directus_files.filename_disk"
            ],
        })
    );
```

The "fields" object recognizes the "id" and "name" fields perfectly. But for the "images.directus_files.filename_disk" it only recognizes "images" as a valid field.

When I ignore the typescript error and run the function everything works perfectly fine. The only issue is that "images.directus_files.filename_disk" is not being recognized as a valid field option. This is the case for all nested relational data beyong the first layer.

**Comment by ChappIO** [comment]
Yeah I have noticed this as well but haven't found out what the typescript types have to be in order for the SDK to understand the nested fields. And I haven't had the time to dive deeper into the issue.

If you find out what the generated types have to look like to make this work, let me know. Otherwise, I will post an update here once I find out the solution.

**Comment by thijserven** [comment]
@ChappIO After digging through the Directus documentation I've found the issue. 

See: https://docs.directus.io/guides/sdk/getting-started.html#read-nested-fields 

Apparently when using a schema in the Directus client you can't use the `"images.directus_files.filename_disk"` notation anymore. Instead you need to set up relational fields according to the example in the docs link above.

So in my case changing the code example of my first comment to this did the trick:

```js
    const items = await directus.request(
        readItems("items", {
            fields: [
                "id",
                "name",
                 { images: [{ directus_files: ["filename_disk"] }] }
            ],
        })
    );
```

When setting up de `fields` parameter like this, everything is typed according to the provided schema and Typescript has stopped complaining.

**Comment by ChappIO** [comment]
Oh very good to know! Thank you for figuring this out. I will change it in my own projects as well. No more ts-ignore :D
